PUT http://localhost:3333/users
Content-Type: application/json

{
  "email" : "Mario",
  "password": "123456",
  "catalog" : [
    "Naruto",
    "Dragon Ball",
    "One Piece"
  ]
}

###

GET http://localhost:3333/users

###

POST http://localhost:3333/users/1541cf52-3080-4d5f-9dbf-999d558cefa1/catalog
Content-Type: application/json

{
  "catalog": "Bleach"
}

###

DELETE http://localhost:3333/users/1541cf52-3080-4d5f-9dbf-999d558cefa1/catalog
Content-Type: application/json

{
  "catalog": "Bleach"
}